### ISSUE TITLE
guides/client/basic: basic example doesn't compile

### ISSUE THREAD

**Issue by alexsasharegan** [hyperium/hyper#1504]
As a newcomer to Rust, I'm just hacking on the client trying to see how I can make requests with hyper. The getting started docs for the client start like this:
> Now, we’ll make a request in the `main` of our program.

This makes me think I can stuff the code into main (minus import and use statements). Doing this, I receive compilation errors because the question mark operator isn't allowed in `main` since main returns an empty tuple and not the corresponding result type.

This doesn't seem too bad, but trying to extract things out into a function means I need to define the return type, which means I need to dig into returning a client, which means I need to resolve its generics... All of this is hard for a beginner.

It would be awesome if the end of the getting started page showed a snippet with a full file that compiles. I imagine there might be other sections of docs that could use this treatment besides the client. I just wanted to chime in with a beginner's perspective here. It's totally possible I'm missing something, but if so, maybe that thing should be stated more clearly.

For reference, here's how I put together the getting started example:

```rust
extern crate futures;
extern crate hyper;
extern crate tokio_core;

use std::io::{self, Write};
use futures::{Future, Stream};
use hyper::Client;
use tokio_core::reactor::Core;

fn main() {
  let mut core = Core::new()?;
  let client = Client::new(&core.handle());

  let uri = "http://httpbin.org/ip".parse()?;
  let work = client.get(uri).and_then(|res| {
    println!("Response: {}", res.status());

    res.body()
      .for_each(|chunk| io::stdout().write_all(&chunk).map_err(From::from))
  });
  core.run(work)?;
}

```

And the compiler error:

```
error[E0277]: the `?` operator can only be used in a function that returns `Result` (or another type that implements `std::ops::Try`)
  --> src/main.rs:11:17
   |
11 |     let mut core = Core::new()?;
   |                    ^^^^^^^^^^^^ cannot use the `?` operator in a function that returns `()`
   |
   = help: the trait `std::ops::Try` is not implemented for `()`
   = note: required by `std::ops::Try::from_error`

error[E0277]: the `?` operator can only be used in a function that returns `Result` (or another type that implements `std::ops::Try`)
  --> src/main.rs:14:12
   |
14 |     let uri = "http://httpbin.org/ip".parse()?;
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot use the `?` operator in a function that returns `()`
   |
   = help: the trait `std::ops::Try` is not implemented for `()`
   = note: required by `std::ops::Try::from_error`

error[E0277]: the `?` operator can only be used in a function that returns `Result` (or another type that implements `std::ops::Try`)
  --> src/main.rs:21:2
   |
21 |     core.run(work)?;
   |     ^^^^^^^^^^^^^^^ cannot use the `?` operator in a function that returns `()`
   |
   = help: the trait `std::ops::Try` is not implemented for `()`
   = note: required by `std::ops::Try::from_error`
```

**Comment by seanmonstar** [comment]
Thanks! Indeed, many have reported this issue, I've so far in the past held out that `fn main() -> Result<...>` would be here soon, and the problem could start to go away... perhaps that was foolish of me, and this should be fixed to help newcomers, like you said!

**Comment by smithsps** [comment]
Looks like there is an existing pull request for this over at https://github.com/hyperium/hyperium.github.io/pull/27 via @lePereT

**Comment by seanmonstar** [comment]
I've updated the guides to work with 0.12.x, and I believe I addressed this while doing so.
