### ISSUE TITLE
Unable to find Tower middleware signature constraints that works with both Axum and Hyper

### ISSUE THREAD

**Issue by francoposa** [hyperium/hyper#3508]
**Version**
hyper 1, http 1

**Platform**
Linux thinkpad-z13 6.6.6-1-default #1 SMP PREEMPT_DYNAMIC Mon Dec 11 09:46:39 UTC 2023 (a946a9f) x86_64 x86_64 x86_64 GNU/Linux

**Description**
Attempting to update a tower middleware to work with axum 0.7 and hyper 1.0
Previously works with axum 0.6 and hyper 0.14

I had to unconstrain the Body parameter for Service to be accepted by axum, but now hyper 0.14 _and_ hyper 1.0 won't accept it:
https://github.com/francoposa/tower-otel-http-metrics/pull/4/files

I based the generics signatures off of the [tower-http request-id middleware](https://github.com/tower-rs/tower-http/blob/main/tower-http/src/timeout/service.rs).

Axum 0.7 server code that now works with the updated middleware:
https://github.com/francoposa/tower-otel-http-metrics/blob/axum-0.7-compatibility/examples/axum-http-service/src/main.rs

Hyper 0.14 server code that now won't work with the middleware:
https://github.com/francoposa/tower-otel-http-metrics/blob/axum-0.7-compatibility/examples/tower-http-service/src/main.rs

I also tried the hyper 1.0 server guide, and get the same issue - in fact the tower http request ID middleware also has the same issue.
I thus far have not found any middleware code examples anywhere that work with both axum 0.7 and hyper 1.0.

```
error[E0277]: the trait bound `HTTPMetricsService<ServiceFn<fn(hyper::Request<Body>) -> impl Future<Output = Result<Response<Body>, Infallible>> {handle}>>: Service<hyper::Request<Body>>` is not satisfied
  --> src/main.rs:65:38
   |
65 |     let server = Server::bind(&addr).serve(make_service);
   |                                      ^^^^^ the trait `Service<hyper::Request<Body>>` is not implemented for `HTTPMetricsService<ServiceFn<fn(hyper::Request<Body>) -> impl Future<Output = Result<Response<Body>, Infallible>> {handle}>>`
   |
   = help: the trait `Service<http::request::Request<ReqBody>>` is implemented for `HTTPMetricsService<S>`
   = note: required for `HTTPMetricsService<ServiceFn<fn(hyper::Request<Body>) -> impl Future<Output = Result<Response<Body>, Infallible>> {handle}>>` to implement `hyper::service::http::HttpService<Body>`
   = note: required for `Shared<HTTPMetricsService<ServiceFn<fn(hyper::Request<Body>) -> impl Future<Output = Result<Response<Body>, Infallible>> {handle}>>>` to implement `hyper::service::make::MakeServiceRef<AddrStream, Body>`
```
