### ISSUE TITLE
The update to socket2 v0.4 raised the MSRV to 1.46

### ISSUE THREAD

**Issue by nickelc** [hyperium/hyper#2482]
CI didn't catch it because MSRV is tested only with default features.
```
$ cargo +1.45.2 c --features tcp
    Checking socket2 v0.4.0
    Checking tokio v1.4.0
error[E0658]: `match` is not allowed in a `const fn`
   --> /.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.0/src/lib.rs:156:9
    |
156 | /         match address {
157 | |             SocketAddr::V4(_) => Domain::IPV4,
158 | |             SocketAddr::V6(_) => Domain::IPV6,
159 | |         }
    | |_________^
    |
    = note: see issue #49146 <https://github.com/rust-lang/rust/issues/49146> for more information
```

**Comment by seanmonstar** [comment]
Oh shucks. Probably need to revert that commit for now, unless socket2 can reduce it's dependent features, but I doubt it.

cc @Thomasdezeeuw

**Comment by Thomasdezeeuw** [comment]
I'm afraid socket2's MSRV can't easily be lowered. Rust 1.46 was released August 27th, if that isn't old enough then I guess it needs to be reverted.

**Comment by johanot** [comment]
You could just pin socket2 v0.3 for now? v0.3.X is still actively maintained in a separate branch, afaik.

**Comment by Thomasdezeeuw** [comment]
> You could just pin socket2 v0.3 for now? v0.3.X is still actively maintained in a separate branch, afaik.

v0.3 is still being maintained, but I prefer the ecosystem to move to v0.4.

**Comment by johanot** [comment]
Fair! Works for me with Rust 1.50, but not 1.49, fwiw..

**Comment by Thomasdezeeuw** [comment]
@johanot are you sure? Socket2 should work with 1.46 and up.

**Comment by johanot** [comment]
Ok, that's embarrassing. My shell environment was polluted. Can confirm it works fine with 1.49 as well. Sorry, don't mind me :)

**Comment by seanmonstar** [comment]
That's a fair point, we've mostly adopted Tokio's policy of working on rustc at least 6 months old. It could be the answer is just bump CI.

**Comment by Thomasdezeeuw** [comment]
I could send a pr to bump the MSRV to 1.46. @nickelc do you need 1.45 support?

**Comment by nickelc** [comment]
> I could send a pr to bump the MSRV to 1.46. @nickelc do you need 1.45 support?

no, i only noticed the issue.

**Comment by Thomasdezeeuw** [comment]
Created #2486 to increase the MSRV.

**Comment by ramosbugs** [comment]
hi folks, this issue unfortunately affects the MSRV of downstream crates as well. in my case, both the `oauth2` and `openidconnect` crates (that I maintain) had their MSRV broken by this change. would it be possible to revert this and bump `hyper` to 0.15 so that the MSRV follows semver?

**Comment by Thomasdezeeuw** [comment]
> hi folks, this issue unfortunately affects the MSRV of downstream crates as well. in my case, both the `oauth2` and `openidconnect` crates (that I maintain) had their MSRV broken by this change. would it be possible to revert this and bump `hyper` to 0.15 so that the MSRV follows semver?

Although I'm not opposed this, not that I'm making that call. But it's still under active discussion whether or not bumping MSRV is a breaking semver change. Especially past 1.0 that wouldn't make sense IMO.
