### ISSUE TITLE
Serve a file through a readable stream

### ISSUE THREAD

**Issue by gmorer** [hyperium/hyper#2176]
I want to send a file without putting the whole file in memory, for that i use futures-fs who creat a readable stream, but i cant give to a Hyper response, with the Body::wrap_stream function:
Code:
```rust
use hyper::service::{ make_service_fn, service_fn };
use hyper::{ Body, Request, Response, Server };
use futures_fs::FsPool;

type GenericError = Box<dyn std::error::Error + Send + Sync>;
type Result<T> = std::result::Result<T, GenericError>;

async fn serve(fs: FsPool, req: Request<Body>) -> Result<Response<Body>> {
	// let mut not_found = Response::default();
	let stream = fs.read("/tmp/streams/hello_world.html", Default::default());
	Ok(Response::new(Body::wrap_stream(stream)))
}

#[tokio::main]
async fn main() -> Result<()> {
    let addr = ([127, 0, 0, 1], 3000).into();
	let fs = FsPool::default();
    let service = make_service_fn(|_| {
		let fs = fs.clone();
		async move {
			Ok::<_, hyper::Error>(service_fn(move |req| {
				serve(fs.clone(), req)
			})) 
		}
		});
    let server = Server::bind(&addr).serve(service);
    server.await?;
    Ok(())
}
```
I got the following error:
```bash
error[E0277]: the trait bound `futures_fs::read::FsReadStream: futures_core::stream::Stream` is not satisfied
   --> src/main.rs:11:37
    |
11  |     Ok(Response::new(Body::wrap_stream(stream)))
    |                                        ^^^^^^ the trait `futures_core::stream::Stream` is not implemented for `futures_fs::read::FsReadStream`
    | 
   ::: /home/tet/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.4/src/body/body.rs:159:12
    |
159 |         S: Stream<Item = Result<O, E>> + Send + Sync + 'static,
    |            --------------------------- required by this bound in `hyper::body::body::Body::wrap_stream`

error: aborting due to previous error

```

**Comment by nickkuk** [comment]
I think this is because futures-fs crate uses `Future`s and `Stream`s from [futures](https://crates.io/crates/futures) crate of version 0.1
But hyper 0.13 works with futures of version 0.3, these versions are incompatible.

There is a way to convert file into stream by [tokio-util](https://crates.io/crates/tokio-util) crate. I've mentioned it [here](https://github.com/hyperium/hyper/issues/2166#issuecomment-612363623).

**Comment by nickkuk** [comment]
@gmorer, if you still have a questions look at [send_file example](https://github.com/hyperium/hyper/blob/203621e3be6b0dab6b79d1914482c556075a19ff/examples/send_file.rs), it was updated with suggested approach.
