### ISSUE TITLE
hyper client on 0.11.0 returns () on .get()

### ISSUE THREAD

**Issue by laplaceon** [hyperium/hyper#1217]
I tried imitating the getting started guide with the relevant code:

```
let mut core = Core::new().unwrap();
let client = Client::new(&core.handle());
let uri = Uri::from_str("http://hyper.rs").unwrap();
let work = client.get(uri).and_then(move |res| {
	println!("Response: {}", res.status());
});
core.run(work).unwrap();
```

I receive this error:

```Compiling supercell v1.0.0 (file:///root/supercell)
error[E0277]: the trait bound `(): downloader::futures::Future` is not satisfied
  --> src/downloader.rs:41:29
   |
41 |    let work = client.get(uri).and_then(move |res| {
   |                               ^^^^^^^^ the trait `downloader::futures::Future` is not implemented for `()`
   |
   = note: required because of the requirements on the impl of `downloader::futures::IntoFuture` for `()`

error[E0277]: the trait bound `(): downloader::futures::Future` is not satisfied
  --> src/downloader.rs:44:7
   |
44 |    core.run(work).unwrap();
   |         ^^^ the trait `downloader::futures::Future` is not implemented for `()`
   |
   = note: required because of the requirements on the impl of `downloader::futures::IntoFuture` for `()`

error: aborting due to 2 previous errors

error: Could not compile `supercell`.
```
Attempted compile on Rust 1.18.0.

**Comment by seanmonstar** [comment]
My mistake, I'm in the process of getting the guides compiling on CI.

The error is that `and_then` requires the closure to return a future-like thing. It's used for when you need to take a future result, and then do something else asynchronous that creates a new future. If you don't need to create a new future, `map` is slightly easier to work with. To fix your code:

```rust
let work = client.get(uri).and_then(|res| {
    println!("Response: {}", res.status());
    Ok(()) // is Future-like (technically, implements IntoFuture)
});
```
 Or:
```rust
let work = client.get(uri).map(|res| {
    println!("Response: {}", res.status());
    // the implicit () return is fine
});
```

**Comment by laplaceon** [comment]
Ahhh, that explains it. It works as expected now.
